export declare const kJest = "jest";
export declare const kVi = "vi";
export declare const kVitest = "vitest";
export declare const kJSRelativeImportRegex: RegExp;
export declare const kJSOrTSFilepathRegex: RegExp;
export declare const kJSOrTSTestFilepathRegex: RegExp;
export declare const kCaptureDirAndBasenameFromJSOrTSFilepathRegex: RegExp;
export declare const kJSQuoteGlobalRegex: RegExp;
export declare const kTSExtension = ".ts";
export declare const kDTSExtension = ".d.ts";
export declare const kJSExtension = ".js";
export declare const kCJSExtension = ".cjs";
export declare const kCTSExtension = ".cts";
export declare const kMJSExtension = ".mjs";
export declare const kMTSExtension = ".mts";
export declare const kIndex = "index";
export declare const kPosixFolderSeparator = "/";
export declare const kExpectedTestConstructs: string[];
export declare const kNewline = "\n";
export declare const kWhitespaceRegex: RegExp;
export declare const kSemicolonRegex: RegExp;
export declare const kSemicolon = ";";
export declare const kExtensions: string[];
export declare const kAppliesToMessage: string;
export declare const kCmdVars: {
    readonly folder: "-f";
    readonly from: "--from";
    readonly to: "--to";
};
export declare const kRPackageJsonFilepath = "./rpackage.json";
export declare const kRequire = "require";
